print ("Hello dear person!   ")
Firstname=input("Please enter your Firstname   ")
Lastname=input("Please enter your Lastname   ")
age= int(input("please enter your age   "))
height= float(input("Please enter your height   "))
print (f"Hello, {Firstname} {Lastname}! Your age is {age} and your height is {height}")
print(type(Lastname))
print(type(age))
print(age+2)
print(f"You grew fast! {(height+0.125):.2f}")