print ("Hello dear person!   ")
Firstname=input("Please enter your Firstname   ")
Lastname=input("Please enter your Lastname   ")
age=input("please enter your age   ")
#print ("Hello, " + Firstname + "" + Lastname + "!")
print (f"Hello, {Firstname} {Lastname}! Your age is {age}.")